# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'О клубе',   url: 'about.html'}
- {name: 'Статьи', url: 'writing.html'}
- {name: 'События', url: 'events.html'}
- {name: 'Проекты', url: 'projects'}
- {name: 'Контакты', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/'}
- {icon: 'twitter',    link: 'https://twitter.com/'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/'}
- {icon: 'envelope',   link: 'mailto:bolzman-club@yandex.ru'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Следующая'
  previous_page: 'Предыдущая'

sharing_button_prompt: 'Поделиться!'

related_posts: 'Вам также может быть интересно:'

post_date_prefix: 'Дата публикации:'

slogan: 'Вносите определенность!'
